import type { DashboardRequest } from './demoTypes';

export const mockRequests: DashboardRequest[] = [
  {
    id: 'REQ-1001',
    requester: 'Ana Souza',
    department: 'Finanças',
    amount: 1240,
    submittedAt: '2026-06-03',
    status: 'Open',
    urgent: true,
    summary: 'Substituição de notebook e dock station.',
  },
  {
    id: 'REQ-1002',
    requester: 'Bruno Lima',
    department: 'Operações',
    amount: 4800,
    submittedAt: '2026-06-04',
    status: 'Approved',
    urgent: false,
    summary: 'Pacote de viagem e hospedagem para equipe de campo.',
  },
  {
    id: 'REQ-1003',
    requester: 'Carla Mendes',
    department: 'Pessoas',
    amount: 760,
    submittedAt: '2026-06-05',
    status: 'Pending',
    urgent: false,
    summary: 'Taxas anuais de certificação de treinamento.',
  },
  {
    id: 'REQ-1004',
    requester: 'Diego Santos',
    department: 'Tecnologia',
    amount: 2180,
    submittedAt: '2026-06-06',
    status: 'Rejected',
    urgent: false,
    summary: 'Solicitação de ferramentas externas sem aprovação.',
  },
  {
    id: 'REQ-1005',
    requester: 'Elisa Rocha',
    department: 'Finanças',
    amount: 3190,
    submittedAt: '2026-06-08',
    status: 'Open',
    urgent: true,
    summary: 'Patrocínio de conferência e aprovação de viagem.',
  },
  {
    id: 'REQ-1006',
    requester: 'Felipe Costa',
    department: 'Comercial',
    amount: 980,
    submittedAt: '2026-06-09',
    status: 'Approved',
    urgent: false,
    summary: 'Reembolso de quilometragem para visita a cliente.',
  },
  {
    id: 'REQ-1007',
    requester: 'Giulia Nunes',
    department: 'Operações',
    amount: 1520,
    submittedAt: '2026-06-10',
    status: 'Pending',
    urgent: true,
    summary: 'Atualização do inventário do armazém.',
  },
  {
    id: 'REQ-1008',
    requester: 'Henrique Alves',
    department: 'Tecnologia',
    amount: 2640,
    submittedAt: '2026-06-11',
    status: 'Approved',
    urgent: false,
    summary: 'Revisão de segurança e reforço de endpoints.',
  },
];
